"""常量

"""

# 缓存数据路径

# 截面处理的字段列表
CS_FIELD = [
                  # 'adjfactor',
                  'bp',
                  'cashtocurrentdebt',
                  # 'close',
                  'current',
                  'currentdebttodebt',
                  # 'date',
                  # 'ex_rate',
                  # 'ex_rate_20d',
                  'exp_wgt_return_3m',
                  'exp_wgt_return_6m',
                  'fa_debttoeqy',
                  # 'high',
                  # 'ipo_date',
                  # 'last_trade_day',
                  # 'low',
                  # 'maxupordown',
                  'mkt_cap_ard',
                  'ncfp',
                  'ocfp',
                  # 'open',
                  'pb_lf',
                  'pcf_ncf_ttm',
                  'pcf_ocf_ttm',
                  # 'pct_chg',
                  'ps_ttm',
                  'qfa_ocftosales',
                  'qfa_operateincometoebt',
                  'qfa_roe',
                  'return_1m',
                  'return_3m',
                  'return_6m',
                  # 'sec_name',
                  'sp',
                  'std_turn_30d',
                  # 'trade_status',
                  'turn',
                  'turn_5d',
                  # 'volume',
                  'wgt_return_1m',
                  'wgt_return_3m',
                  # 'windcode',
                  'yoy_or',
                  'yoyeps_basic',
                  'yoyocf',
                  'yoyprofit'
                  ]

# 机器学习的特征字段
FEATURE_FIELD = [
                  # 'adjfactor',
                  'bp',
                  'cashtocurrentdebt',
                  # 'close',
                  'current',
                  'currentdebttodebt',
                  # 'date',
                  # 'ex_rate',
                  # 'ex_rate_20d',
                  'exp_wgt_return_3m',
                  'exp_wgt_return_6m',
                  'fa_debttoeqy',
                  # 'high',
                  # 'ipo_date',
                  # 'last_trade_day',
                  # 'low',
                  # 'maxupordown',
                  'mkt_cap_ard',
                  'ncfp',
                  'ocfp',
                  # 'open',
                  'pb_lf',
                  'pcf_ncf_ttm',
                  'pcf_ocf_ttm',
                  # 'pct_chg',
                  'ps_ttm',
                  'qfa_ocftosales',
                  'qfa_operateincometoebt',
                  'qfa_roe',
                  'return_1m',
                  'return_3m',
                  'return_6m',
                  # 'sec_name',
                  'sp',
                  'std_turn_30d',
                  # 'trade_status',
                  'turn',
                  'turn_5d',
                  # 'volume',
                  'wgt_return_1m',
                  'wgt_return_3m',
                  # 'windcode',
                  'yoy_or',
                  'yoyeps_basic',
                  'yoyocf',
                  'yoyprofit'
                  ]
